---
- name: Configure Mellanox SN2100 switches with Cumulus
  hosts: switches
  become: yes
  tasks:

    - name: Set static IP address on eth0
      command: nv set interface eth0 ip address {{ ip_address }}

    - name: Set default gateway
      command: nv set interface eth0 ip gateway 10.10.198.1

    - name: Apply network configuration
      command: nv config apply

    - name: Set hostname
      command: nv set system hostname {{ inventory_hostname }}

    - name: Apply hostname configuration
      command: nv config apply

    - name: Set timezone to Europe/Copenhagen
      command: nv set system timezone Europe/Copenhagen

    - name: Apply timezone configuration
      command: nv config apply

    - name: Verify time settings
      command: date
      register: time_output

    - name: Display current system time
      debug:
        msg: "{{ time_output.stdout }}"
