---
- name: System Update & Maintenance
  become: true
  become_method: sudo
  become_user: root
  hosts: all
  gather_facts: true
  tasks:
    - name: Ensure APT is not locked
      shell: "lsof /var/lib/dpkg/lock || echo 'not locked'"
      register: apt_lock
      changed_when: false

    - name: Fail if APT is locked
      fail:
        msg: "APT is locked, another process might be running updates!"
      when: "'not locked' not in apt_lock.stdout"

    - name: Update apt repo and cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      tags: 
        - update

    - name: Upgrade all packages
      apt:
        name: "*"
        state: latest
        only_upgrade: true
      tags: 
        - upgrade

    - name: Remove unnecessary packages
      apt:
        autoremove: true
        autoclean: true
      tags: 
        - cleanup

    - name: Check if a reboot is needed
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Display reboot message if required
      debug:
        msg: "Reboot required. Proceeding with reboot..."
      when: reboot_required_file.stat.exists

    - name: Reboot if required
      reboot:
        msg: "Reboot initiated by Ansible due to kernel update"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 10
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
      tags: 
        - reboot
